#!/bin/bash

# ==============================================================================
# Monowm Autostart Script
# This script runs programs when monowm starts. Feel free to edit this file.
# Uncomment options if necessary
# ==============================================================================

# Display Settings
# DISPLAY_OUTPUT="eDP-1"
# RESOLUTION="1920x1080"
# DPI="96" #For high resolutions increase this for bigger text
# IDLE_TIME=300 # Time it takes for screen to sleep in seconds (300 seconds = 5 minutes)
#
# xrandr --dpi $DPI
# xset s on
# xset s $IDLE_TIME
# xset +dpms
# xset dpms $IDLE_TIME $IDLE_TIME $IDLE_TIME
# if command -v xrandr >/dev/null 2>&1; then
#     xrandr --output "$DISPLAY_OUTPUT" --mode "$RESOLUTION"
# fi
