# ==============================================================================
# Monowm Bar Configuration (bar.conf)
# ==============================================================================

# General Bar Settings
bar_enabled = 1
bar_height = 24
bar_font_name = JetBrainsMono Nerd Font
bar_font_size = 14
bar_update_interval = 5 # In seconds. Lower for worst performance but more responsive bar updates
bar_position = top  # Options: top, bottom


# Bar Colors (Hex formats or '-' for default)
bar_color_active_fg = #ffffff
bar_color_active_bg = #555555
bar_color_inactive_fg = #aaaaaa
bar_color_inactive_bg = -

# Bar Module Positions ('l' = left, 'c' = center, 'r' = right)
bar_show_windows = 1
bar_windows_position = l

bar_show_time = 1
bar_time_position = r
bar_time_format = %I:%M %p

bar_show_battery = 1
bar_battery_position = r
bar_battery_path = /sys/class/power_supply/BAT0
bar_battery_icon_full = 
bar_battery_icon_75 = 
bar_battery_icon_50 = 
bar_battery_icon_25 = 
bar_battery_icon_empty = 
bar_battery_icon_charging = 

bar_show_volume = 0
bar_volume_position = r
bar_volume_cmd = wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2 * 100)}'
bar_volume_mute_cmd = wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo "yes" || echo "no"
bar_volume_icon_high = 󰕾
bar_volume_icon_med = 󰖀
bar_volume_icon_low = 󰕿
bar_volume_icon_mute = 󰝟

# Default Application Icon
default_icon = 

# Application Icon Mappings
# Format: icon = res_class : icon_string
icon = firefox : 
icon = st : 
icon = alacritty : 
icon = kitty : 
icon = chromium : 
