# ==============================================================================
# Monowm Core Configuration (config.conf)
# ==============================================================================

# Maximum number of windows that can be open at the same time (max 128)
max_windows = 9

# Internal Window Manager Keybindings
# Format: modifiers+keysym (modifiers can be: super, shift, control, alt)
# To use function keys, make sure you capitalize f (Ex. F4)

#Close Window
bind_quit = super+q

# Set to 0 if you're gonna use alttab program, set to 1 to use native window cycler
cycle_enabled = 0
bind_cycle = super+Tab

#mod key for window switcher. For instance if you set to super+Shift, you can use super+Shift 1-9 to switch windows
bind_switch_window_mod = super+Shift

#Reload Config or Bar after editing
bind_reload = super+Shift+r

#Hide Bar (I guess you can call it full screen)
bind_toggle_bar = super+Shift+b

# Autostart Commands (run when monowm starts)
# You can also add more complex autostart commands in ~/.config/monowm/autostart
run = dunst
run = feh --bg-fill ~/.config/monowm/bg.png

#uncomment this if you want to use alttab program as a window switcher (here its binded as super tab)
# run = alttab -w 1 -mk Super_L -t 224x256 -i 64x64 -font 'xft:sans-20'

# Custom Hotkeys
# Format: keybind = modifiers+keysym : command
keybind = super+Return : alacritty
keybind = super+space : dmenu_run -fn 'monospace-14'
keybind = super+b : chromium
keybind = XF86AudioRaiseVolume : ~/.local/bin/monowm-volume up
keybind = XF86AudioLowerVolume : ~/.local/bin/monowm-volume down
keybind = XF86AudioMute : ~/.local/bin/monowm-volume mute
keybind = XF86AudioMicMute : wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
keybind = XF86MonBrightnessUp : ~/.local/bin/monowm-brightness up
keybind = XF86MonBrightnessDown : ~/.local/bin/monowm-brightness down
